wip

diff --git a/bin/db/db-setup b/bin/db/db-setup
--- a/bin/db/db-setup
+++ b/bin/db/db-setup
@@ -1,5 +1,5 @@
 #! /usr/bin/bash
--e # stop if it fails at any point
+set -e # stop if it fails at any point
 
 CYAN='\033[1;36m'
 NO_COLOR='\033[0m'
@@ -7,9 +7,9 @@ LABEL="db-setup"
 printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"
 
 bin_path="$(realpath .)/bin/db"
-
+echo $bin_path
 source "$bin_path/db-drop"
 source "$bin_path/db-create"
 source "$bin_path/db-schema-load"
 source "$bin_path/db-seed"
-python "$bin_path/update_cognito_user_ids"
+python "$bin_path/update"
